version: '2.4'
services:
  dev:
    build:
      context: ..
      target: dev
    command: /bin/sh -c "while sleep 1; do :; done"
    working_dir: /home/node/app
    environment:
      PYTHONPATH: /root/workspace/src:/opt/spark/python/:/opt/spark/python/lib/py4j-0.10.9.3-src.zip
      HISTFILE: '/root/.bashhistory/.bash_history'
    volumes:
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh
      - ..:/home/node/app
 
volumes:
  bash-history:
