from datetime import datetime

test_definitions = [
    {
        "companyId": "tilting_point_mjs4k",
        "projectId": "spongebob_x7d9q",
        "name": "spongebob_test_1",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": None,
        "min_first_login_date": datetime(2022, 11, 17),
        "max_first_login_date": datetime(2028, 1, 31),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 2.313530563844,
                        "bIg": 0.7354956768576817,
                        "mu": 1.870407,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 2.313530563844,
                        "bIg": 0.7354956768576817,
                        "mu": 1.870407,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 11, 17),
    },
    {
        "companyId": "tilting_point_mjs4k",
        "projectId": "spongebob_x7d9q",
        "name": "spongebob_test_2",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": True,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2022, 11, 17),
        "max_first_login_date": datetime(2028, 1, 31),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 3.7160685601439996,
                        "bIg": 3.5580172209659175,
                        "mu": 2.230539,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 3.7160685601439996,
                        "bIg": 3.5580172209659175,
                        "mu": 2.230539,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 11, 17),
    },
    {
        "companyId": "tilting_point_mjs4k",
        "projectId": "terragenesis_m89uz",
        "name": "terragenesis_test_1",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": None,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.232343254560153,
                        "bIg": 4.829453191131073,
                        "mu": 1.765416,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.232343254560153,
                        "bIg": 4.829453191131073,
                        "mu": 1.765416,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 11, 1),
    },
    {
        "companyId": "tilting_point_mjs4k",
        "projectId": "terragenesis_m89uz",
        "name": "terragenesis_test_2",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 5.596100609833022,
                        "bIg": 8.715763630891116,
                        "mu": 2.097467,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 5.596100609833022,
                        "bIg": 8.715763630891116,
                        "mu": 2.097467,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 11, 1),
    },
    {
        "companyId": "tinysoft_a9kwp",
        "projectId": "heroes_magic_war_h2sln",
        "name": "tinysoft_test_1",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": None,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.473413357537831,
                        "bIg": 5.462668181831057,
                        "mu": 2.322528,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.473413357537831,
                        "bIg": 5.462668181831057,
                        "mu": 2.322528,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 9, 22),
    },
    {
        "companyId": "tinysoft_a9kwp",
        "projectId": "heroes_magic_war_h2sln",
        "name": "tinysoft_test_2",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": True,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": None,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.620776355562269,
                        "bIg": 5.861606789147952,
                        "mu": 2.05869,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.620776355562269,
                        "bIg": 5.861606789147952,
                        "mu": 2.05869,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 9, 22),
    },
    {
        "companyId": "tinysoft_a9kwp",
        "projectId": "heroes_magic_war_h2sln",
        "name": "tinysoft_test_3",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2022, 9, 22),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 9.473114072847384,
                        "bIg": 23.16294943475726,
                        "mu": 2.475696,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 9.473114072847384,
                        "bIg": 23.16294943475726,
                        "mu": 2.475696,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 9, 22),
    },
    {
        "companyId": "tinysoft_a9kwp",
        "projectId": "heroes_magic_war_h2sln",
        "name": "tinysoft_test_4",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": True,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2022, 9, 22),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 7.335778517365857,
                        "bIg": 14.635207493416793,
                        "mu": 2.046439,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 7.335778517365857,
                        "bIg": 14.635207493416793,
                        "mu": 2.046439,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2022, 9, 22),
    },
    {
        "companyId": "century_games_ncmgu",
        "projectId": "bingo_aloha_r3g9v",
        "name": "bingo_aloha_test_1",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": 7,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.205832361197443,
                        "bIg": 4.761316599857369,
                        "mu": 1.973709,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.205832361197443,
                        "bIg": 4.761316599857369,
                        "mu": 1.973709,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2023, 2, 1),
    },
    {
        "companyId": "century_games_ncmgu",
        "projectId": "bingo_aloha_r3g9v",
        "name": "bingo_aloha_test_2",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": True,
        "datapointType": "one_datapoint_per_user_per_meta_date",
        "nDaysSpend": None,
        "min_first_login_date": datetime(2010, 1, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.033864309549489,
                        "bIg": 4.32670355669653,
                        "mu": 2.000769,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 4.033864309549489,
                        "bIg": 4.32670355669653,
                        "mu": 2.000769,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2023, 2, 1),
    },
    {
        "companyId": "century_games_ncmgu",
        "projectId": "bingo_aloha_r3g9v",
        "name": "bingo_aloha_test_3",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": False,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2023, 2, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 9.356911467857774,
                        "bIg": 22.666975031966572,
                        "mu": 2.397025,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 9.356911467857774,
                        "bIg": 22.666975031966572,
                        "mu": 2.397025,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2023, 2, 1),
    },
    {
        "companyId": "century_games_ncmgu",
        "projectId": "bingo_aloha_r3g9v",
        "name": "bingo_aloha_test_4",
        "abTestId": "test",
        "createdAt": "whatever, dont really care",
        "createdBy": "whatever, dont really care",
        "active": "true",
        "schedulerConfig": "whatever, dont really care",
        "winsorizedSpend": True,
        "presonalizedSpend": True,
        "datapointType": "one_datapoint_per_user",
        "nDaysSpend": 30,
        "min_first_login_date": datetime(2023, 2, 1),
        "max_first_login_date": datetime(2028, 1, 1),
        "variantsDefinition": {
            "variant1": {
                "name": "P",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 8.379021499427374,
                        "bIg": 18.636991564319803,
                        "mu": 2.269493,
                        "w": 10,
                    },
                },
            },
            "variant2": {
                "name": "C",
                "parameters": {
                    "prior": {
                        "aBeta": 1,
                        "bBeta": 1,
                        "aIg": 8.379021499427374,
                        "bIg": 18.636991564319803,
                        "mu": 2.269493,
                        "w": 10,
                    },
                },
            },
        },
        "testStartDate": datetime(2023, 2, 1),
    },
]
