name: Build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      REPOSITORY_NAME: assetario/ab-testing
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_ML_LIB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Image tags
        run: |
          echo "GIT_SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's#/#__#g')" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ASSETS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ASSETS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ ! startsWith(github.ref, 'refs/heads/renovate') }}
          build-args: |
            "SENTRY_RELEASE=${{ github.sha }}"
          ssh: |
            "default"
          tags: |
            "${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}-${{ env.GIT_SHORT_SHA }}-${{ env.GIT_BRANCH }}"
            "${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ env.GIT_BRANCH }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
